language: cpp
compiler:
  - gcc
  - clang
env:
  global:
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release
before_script: cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE .
script:
  - make
  - make test

