# build platform, i.e. Win32 (instead of x86), x64, Any CPU. This setting is optional.
platform: 
  - Win32
  - x64

# build Configuration, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

# clone directory
clone_folder: c:\projects\dart

# branches to build
branches:
  # whitelist
  # only:
  #   - master
  # blacklist
  except:
    - gh-pages

# scripts to run before build
before_build:
  - echo %CD%
  - cmd: cd c:\projects\dart
  - cmd: md build
  - cmd: cd build
  - cmd: if "%platform%"=="Win32" cmake -G "Visual Studio 11" ..
  - cmd: if "%platform%"=="x64" cmake -G "Visual Studio 11 Win64" ..
  
build:
  project: C:\projects\dart\build\dart.sln
  
test_script:
  - cmd: ctest -VV
